name: Endor Labs - Java SCA Scan on PR
on:
  workflow_dispatch
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Used for keyless authentication with Endor Labs
      contents: read
      issues: write # Required to automatically comment on PRs for new policy violations
      pull-requests: write # Required to automatically comment on PRs for new policy violations
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: microsoft
            java-version: "17"

        - name: Compile Package
          run: mvn clean install
            
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            scan_summary_output_type: "table"
            enable_pr_comments: true
            enable_github_action_token: true
            github_token: ${{ secrets.GH_TOKEN }}
            scan_dependencies: true
            #scan_secrets: true <-- Uncomment to enable secrets scanning
            #scan_git_logs: true <-- Uncomment to scan git logs for committed secrets
            #additional_args: "--tools --github --ghactions" <-- Uncomment to scan identified tools, RSPM, and GH Action Vulnerabilities
            tags: "actor = ${{ github.actor }},run-id = ${{ github.run_id }},event name = ${{ github.event_name }},workflow = ${{ github.workflow }},github sha = ${{ github.sha }}"
