
name: Endor SCA and Validating Policy
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication with Endor Labs
      issues: write # Required to automatically comment on PRs for new policy violations

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Endor Scan
      uses: endorlabs/github-action@main
      with:
        namespace: ${{ secrets.ENDOR_NAMESPACE }}
        scan_dependencies: true
        scan_secrets: true
        pr: false
        enable_github_action_token: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        log_verbose: true
    
    - name: Evaluate policy against this project
      run: |
          endorctl validate policy \
          -n ${{ secrets.ENDOR_NAMESPACE }} \
          --enable-github-action-token=true \
          --policy-uuid=<YOUR_POLICY_UUID1,YOUR_POLICY_UUID2> \
          --output-type=json \
          --filter='meta.name matches ${{ github.event.repository.name }}'


          
