name: Endor SCA and Container Scanning
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication with Endor Labs
      issues: write # Required to automatically comment on PRs for new policy violations

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set up Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
      with:
        java-version: '21'
        distribution: 'microsoft'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Endor Scan
      uses: endorlabs/github-action@802fa65ba7c140405ee52d1c806cfdb647f8f743 # v1.1.4
      with:
        namespace: 'arsalan-learn'
        scan_dependencies: true
        scan_secrets: true
        pr: false
        enable_github_action_token: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        log_verbose: true
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
    
    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push
      uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # v6.12.0
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:your_tag
          
    - name: Scan container
      uses: endorlabs/github-action@802fa65ba7c140405ee52d1c806cfdb647f8f743 # v1.1.4
      with:
        namespace: 'arsalan-learn'
        scan_secrets: false
        scan_dependencies: false
        scan_container: true
        pr: false
        enable_github_action_token: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        log_verbose: true
        log_level: "info"
        scan_summary_output_type: "table"
        image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:your_tag
