variables:
    ENDOR_NAMESPACE: "your-namespace" # Insert your Endor Labs namespace here
    ENDOR_API_CREDENTIALS_KEY: $ENDOR_API_KEY
    ENDOR_API_CREDENTIALS_SECRET: $ENDOR_API_SECRET

image: node:latest

stages:
  - build
  - endorScan

# Build steps for your application
build_job:
  stage: build
  script:
    - npm install

endorScan:
  stage: endorScan

  before_script:
    # Download and scan with endorctl
    - npm install -g endorctl
  
  script:
    - endorctl scan 
