name: Endor Labs - SCA Scan on Main
on:
  workflow_dispatch
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
    
        - name: Install Python Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: microsoft
            java-version: "21"

        - name: Compile Java Package
          run: mvn clean install

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: package-lock.json
          
        - name: Build npm Dependencies
          run: npm ci

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.22.4'
          
        - name: Go Build 
          run: go build
            
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@v1.1.4
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            pr: false
            enable_github_action_token: true
            scan_dependencies: true
            # scan_secrets: true <-- Uncomment to enable secrets scanning
            # scan_git_logs: true <-- Uncomment to scan git logs for committed secrets
            # scan_github_actions: true <-- Uncomment to scan GH Action Vulnerabilities
            # scan_tools: true <-- Uncomment to scan identified tools
            additional_args: "--as-default-branch" # Additional parameters can be passed with whitespace separation, for example: --github to enable RSPM
