name: Endor Labs - Java SCA Scan on Main Branch
on:
  workflow_dispatch
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

        - name: Checkout Repository
          uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
          
        - name: Setup Java
          uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
          with:
            distribution: microsoft
            java-version: "21"

        - name: Compile Package
          run: mvn clean install
            
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@802fa65ba7c140405ee52d1c806cfdb647f8f743 # v1.1.4
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            pr: false
            enable_github_action_token: true
            scan_dependencies: true
            # scan_secrets: true <-- Uncomment to enable secrets scanning
            # scan_git_logs: true <-- Uncomment to scan git logs for committed secrets
            # scan_github_actions: true <-- Uncomment to scan GH Action Vulnerabilities
            # scan_tools: true <-- Uncomment to scan identified tools
            additional_args: "--as-default-branch" # Additional parameters can be passed with whitespace separation, for example: --github to enable RSPM