# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'

# Implement and scan with Endor Labs after your build is complete
- script: |
    curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
  displayName: 'Download the Endor Labs CLI'

- script: |
    echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c
  displayName: 'Verify the checksum of the binary'
    
- script: |
    chmod +x ./endorctl
  displayName: 'Modify the permissions of the binary to ensure it is executable'
    
- script: |
    ./endorctl scan --api-key $(ENDOR_API_KEY) --api-secret $(ENDOR_API_SECRET) -n your namespace
  displayName: 'Run a scan against the repository using your API key & secret pair'