variables:
    ENDOR_NAMESPACE: "your-namespace" # Insert your Endor Labs namespace here
    ENDOR_API_CREDENTIALS_KEY: $ENDOR_API_KEY
    ENDOR_API_CREDENTIALS_SECRET: $ENDOR_API_SECRET

# image: if not already declared

stages:
  - build
  - endorScan

# Build steps for your application

endorScan:
  stage: endorScan
  
  before_script:
    # If npm isn't already on the runner, download and scan with endorctl
    - curl -fsSL https://deb.nodesource.com/setup_current.x | bash
    - apt-get install -y nodejs
    - npm install -g endorctl
  
  script:
    - endorctl scan # For additional capabilities, add: --secrets --tools
