variables:
    ENDOR_NAMESPACE: "your-namespace" # Insert your Endor Labs namespace here
    ENDOR_API_CREDENTIALS_KEY: $ENDOR_API_KEY
    ENDOR_API_CREDENTIALS_SECRET: $ENDOR_API_SECRET

image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - endorScan

# Build steps for your application
build:
  stage: build
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY --use-lock-file'  
    - 'dotnet build --no-restore'

endorScan:
  stage: endorScan

  before_script:
    # Download and scan with endorctl
    - curl -fsSL https://deb.nodesource.com/setup_current.x | bash
    - apt-get install -y nodejs
    - npm install -g endorctl
  
  script:
    - endorctl scan 
